# Dockerfile.analyzer
FROM python:3.11.12-slim-bullseye

WORKDIR /app


COPY requirements.txt ./requirements.txt 
RUN pip install --no-cache-dir -r ./requirements.txt

COPY analyzer.py .

ENV ANALYZER_DB_HOST_DEFAULT="host.docker.internal"
ENV ANALYZER_DB_USER_DEFAULT="root"
ENV ANALYZER_DB_PASSWORD_DEFAULT="" 

ENV ANALYZER_DB_NAME_SHOPIFY_DEFAULT="shopify_data"
ENV ANALYZER_DB_NAME_WOOCOMMERCE_DEFAULT="web_scraping_db"
ENV ANALYZER_DB_NAME_ANALYSIS_DEFAULT="product_analysis_db"

ENV ANALYZER_TOP_K_OVERALL_DEFAULT="20"
ENV ANALYZER_FLAGSHIP_PER_STORE_DEFAULT="3"
ENV ANALYZER_WEIGHT_AVAILABILITY_DEFAULT="0.6"
ENV ANALYZER_WEIGHT_PRICE_DEFAULT="0.4"
ENV ANALYZER_DB_BATCH_SIZE_DEFAULT="500"


ENV FLASK_PORT="5003" 

EXPOSE ${FLASK_PORT}


CMD python ./analyzer.py \
    --db_host "${DB_HOST:-$ANALYZER_DB_HOST_DEFAULT}" \
    --db_user "${DB_USER:-$ANALYZER_DB_USER_DEFAULT}" \
    --db_password "${DB_PASSWORD:-$ANALYZER_DB_PASSWORD_DEFAULT}" \
    --db_name_shopify "${DB_NAME_SHOPIFY:-$ANALYZER_DB_NAME_SHOPIFY_DEFAULT}" \
    --db_name_woocommerce "${DB_NAME_WOOCOMMERCE:-$ANALYZER_DB_NAME_WOOCOMMERCE_DEFAULT}" \
    --db_name_analysis "${DB_NAME_ANALYSIS:-$ANALYZER_DB_NAME_ANALYSIS_DEFAULT}" \
    --top_k_overall "${TOP_K_OVERALL:-$ANALYZER_TOP_K_OVERALL_DEFAULT}" \
    --flagship_per_store "${FLAGSHIP_PER_STORE:-$ANALYZER_FLAGSHIP_PER_STORE_DEFAULT}" \
    --weight_availability "${WEIGHT_AVAILABILITY:-$ANALYZER_WEIGHT_AVAILABILITY_DEFAULT}" \
    --weight_price "${WEIGHT_PRICE:-$ANALYZER_WEIGHT_PRICE_DEFAULT}" \
    --db_batch_size "${DB_BATCH_SIZE:-$ANALYZER_DB_BATCH_SIZE_DEFAULT}"